#!/usr/bin/env python
import sys
from MineBot import *

if(len(sys.argv) == 4):
    try:
        xFieldSize = int(sys.argv[1])
        yFieldSize = int(sys.argv[2])
        numMines = int(sys.argv[3])
    except:
        print 'Run as ./MineBot-cli <FieldSizeX> <FieldSizeY> <NumMines>'
        sys.exit()
else:
    xFieldSize = 9
    yFieldSize = 9
    numMines = 10

game = MineGame.MineGame()
game.InitGame(xFieldSize, yFieldSize, numMines)
game.DisplayGrid()
