#!/usr/bin/env python
import sys
from MineBot import *

if(len(sys.argv) == 4):
    try:
        x_field_size = int(sys.argv[1])
        y_field_size = int(sys.argv[2])
        mine_count = int(sys.argv[3])
    except:
        print 'Run as ./MineBot-cli <FieldSizeX> <FieldSizeY> <NumMines>'
        sys.exit()
else:
    x_field_size = 9
    y_field_size = 9
    mine_count = 10

game = MineGame.MineGame()
game.init_game(x_field_size, y_field_size, mine_count)
game.display_grid()
state = game.get_grid_state()
game.display_grid_state()
